import './globals.css'
import type { Metadata } from 'next'
import { Inter, Antonio, League_Spartan } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })
const antonio = Antonio({ subsets: ['latin'], variable: '--antonio-font' })
const spartan = League_Spartan({ subsets: ['latin'] })


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
console.log(antonio)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(antonio)
  console.log('i am a horse')
  return (
    <html lang="en">
      <body className={`${inter.className} ${antonio.className} ${spartan.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
